#!/bin/bash
# Single source of truth for the Prisma schema.
#
# apps/api/prisma/schema.prisma is CANONICAL — edit only that file.
# apps/worker/prisma/schema.prisma is a stamped copy (worker needs a local
# schema so `prisma generate` works inside its own folder / Docker context).
#
# Usage:
#   bash scripts/sync-prisma-schema.sh          # copy api schema -> worker
#   bash scripts/sync-prisma-schema.sh --check  # exit 1 if worker copy is stale

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/apps/api/prisma/schema.prisma"
DEST="$ROOT/apps/worker/prisma/schema.prisma"

if [ ! -f "$SRC" ]; then
  echo "❌ Canonical schema not found: $SRC"
  exit 1
fi

# Build the expected worker copy: warning header + canonical schema
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
cat > "$TMP" <<'EOF'
// ⚠️  GENERATED COPY — DO NOT EDIT THIS FILE.
// Canonical schema: apps/api/prisma/schema.prisma
// Sync with: pnpm run db:sync-schema (runs scripts/sync-prisma-schema.sh)

EOF
cat "$SRC" >> "$TMP"

if [ "$1" == "--check" ]; then
  if diff -q "$TMP" "$DEST" > /dev/null 2>&1; then
    echo "✓ Worker schema is in sync with api schema"
  else
    echo "❌ Schema drift: apps/worker/prisma/schema.prisma is stale (or was edited directly)."
    echo "   Edit apps/api/prisma/schema.prisma, then run: pnpm run db:sync-schema"
    exit 1
  fi
  exit 0
fi

cp "$TMP" "$DEST"
echo "✓ Synced apps/api/prisma/schema.prisma -> apps/worker/prisma/schema.prisma"
